### ISSUE TITLE
'layers' not declared in 'properties:"

### ISSUE THREAD

**Issue by rieje** [urob/zmk-auto-layer#1]
I got the following error building with latest urob/zmk-config:

> devicetree error: 'layers' appears in /behaviors/num_word in /app/build/left/zephyr/zephyr.dts.pre, but is not declared in 'properties:' in /app/zmk-auto-layer/dts/bindings/behaviors/zmk,behavior-auto-layer.yaml

**Comment by urob** [comment]
The behavior changed to specifying the layer as an argument instead of a property. It's a bit hard to say what went wrong without seeing your config. But it sounds like you are trying to use the new module with the old behavior init in your config. 

With the module, there's no need to configure `num_word` at all (if you like the defaults), you just add it to the keymap with `&num_word NAV` as done here: https://github.com/urob/zmk-config/commit/686ecd11fa8aeff7016d7830ad5903ae8e09d252

**Comment by rieje** [comment]
Whoops, I added the parameter but didn't remove the old definition. Closing, sorry.
